//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Website.CheshireWire.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CheshireWireDataEntities : DbContext
    {
        public CheshireWireDataEntities()
            : base("name=CheshireWireDataEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Coach> Coaches { get; set; }
        public virtual DbSet<Fixture> Fixtures { get; set; }
        public virtual DbSet<League> Leagues { get; set; }
        public virtual DbSet<News> News { get; set; }
        public virtual DbSet<Player> Players { get; set; }
        public virtual DbSet<Result> Results { get; set; }
        public virtual DbSet<Team> Teams { get; set; }
    }
}
