//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Website.CheshireWire.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Fixture
    {
        public int Id { get; set; }
        public string OpponentName { get; set; }
        public string Organisation { get; set; }
        public Nullable<System.DateTime> TipOff { get; set; }
        public string AddressLine1 { get; set; }
        public string AddressLine2 { get; set; }
        public string TownCity { get; set; }
        public string Postcode { get; set; }
        public string ImgName { get; set; }
        public int TeamId { get; set; }
    
        public virtual Team Team { get; set; }
        public virtual Result Result { get; set; }
    }
}
